### ISSUE TITLE
Defaults and architecture

### ISSUE THREAD

**Issue by noraj** [Acceis/bqm#28] opened 2023-06-28 13:06 UTC
Asked by @gbe in #25

> 3/ To expand a bit my thoughts above the above 1/, I think that bqm could be started a bit differently.
> 
> Rather than pulling remote sources by default and optionnally merge them with local files, bqm could start as an empty shell.
> Then, the sources are enabled one by one on command-line:
> 
>     -r [data-sets.json]: to pull the remote sources for the optional file data-sets.json. If the switch is set and without a file, then the default dataset file is chosen. I think it may intereset users to set their own data-sets file if they want custom remote sources (for example: a remote file on an intranet).
>     -d <directory>: to include one local set directory.
>     -i <file>: to include one local set file.
> 
> All three switches could be set several times, as there could be several remote sources, several directories, and several individual files.

**Comment by noraj** [comment] 2023-06-28 13:26
> Rather than pulling remote sources by default and optionnally merge them with local files, bqm could start as an empty shell.

This is up for debate, I think default should reflect the most common usages and I think outside of exegol most people just want to grab the maximum of queries and having them sorted and available in bloodhound. So I preferred to fetch them by default and then use a `--no-fetch` or similar flag for the specific use case of Exegol.

> -r [data-sets.json]: to pull the remote sources for the optional file data-sets.json. If the switch is set and without a file, then the default dataset file is chosen. I think it may intereset users to set their own data-sets file if they want custom remote sources (for example: a remote file on an intranet).

Having a flag to provide a custom `data-sets.json` is a good idea.

> All three switches could be set several times, as there could be several remote sources, several directories, and several individual files.

answered in #27

**Comment by gbe** [comment] 2023-06-28 14:45
Agreed, it depends on the direction you wish to give the tool.

I would be happy with a `--no-fetch` or similar. This part of this ticket is a duplicate of https://github.com/Acceis/bqm/issues/26

About the custom `data-sets.json`, yes I figured some users may be interested. Leaving the ticket open for this part.

Thanks again

**Closed as completed** 2023-06-29 13:02 UTC
Labels: enhancement
